OBLContactCenter/Controllers/RoleMenuSettingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OBLContactCenter.EFnClass;
using System.Data;
using OBLContactCenter.Models;
namespace OBLContactCenter.Controllers
{
    [SessionExpire]
    public class RoleMenuSettingController : AppBaseController
    {
        
        CCROLEMENU oCCROLEMENU = null;
        
        public ActionResult Index()
        {
            ViewBag.RoleList = oDBContext.CCROLEs.Where(t => t.ISACTIVE).Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.ROLENAME.ToString()
            });

            ViewBag.MenuList = oDBContext.CCMENUs.Where(t => t.ISACTIVE && t.ISPARENT == true).Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.NAME.ToString()
            });

            return View();
        }


        [HttpGet]
        public ActionResult RoleMenu()
        {
            
            ViewBag.RoleList = oDBContext.CCROLEs.Where(t=>t.ISACTIVE).Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.ROLENAME.ToString()
            });


            return PartialView("_RoleMenuPartial", oCCROLEMENU);
        }

        [HttpGet]
        public ActionResult GetRoleWiseMenuList(int id,int? MenuId)
        {
            var roleMenuItemTemp = oDBContext.CCMENUs.Where(t => t.ISACTIVE);
            if (MenuId.HasValue)
                roleMenuItemTemp =oDBContext.CCMENUs.Where(t => t.ISACTIVE && t.PARENTID == MenuId);
            else
                roleMenuItemTemp =oDBContext.CCMENUs.Where(t => t.ISACTIVE && t.ISPARENT == true);   
            

            var roleMenuItemList = roleMenuItemTemp.Select(t => new RoleMenu
            {
                ID=t.ID,
                MenuName=t.NAME,
                IsParent=t.ISPARENT,
                RoleId=id,
                RoleName = t.CCROLEMENUs.FirstOrDefault(x => x.ROLEID == id).CCROLE.ROLENAME,
                IsAssigned = t.CCROLEMENUs.FirstOrDefault(x => x.ROLEID == id).ISACTIVE
            }).ToList();
            return PartialView("_RMenuAssignListPartial", roleMenuItemList);
        }


        public ActionResult SaveRoleMenuList(List<RoleMenu> oRoleMenuList, FormCollection frmCollection)
        {
            try
            {
                oCurrentUser = (CCUSER)Session["User"];
                var roleId = frmCollection["RoleId"].ToList()[0].ToString();
                //var menuId = frmCollection["MenuId"].ToList()[0].ToString();
                oDBContext.Database.ExecuteSqlCommand("Delete from CCROLEMENU where ROLEID = {0}", roleId);
                oDBContext.SaveChanges();

                var selectedRoleMenuId = frmCollection.GetValues("chkSelect").ToList();
                foreach (string oMenuId in selectedRoleMenuId)
                {
                    CCROLEMENU oCCROLEMENU = new CCROLEMENU();
                    oCCROLEMENU.ROLEID = Convert.ToInt32(roleId);
                    oCCROLEMENU.MENUID = Convert.ToInt32(oMenuId);
                    oCCROLEMENU.ISACTIVE = true;
                    oCCROLEMENU.CREATEDBY = oCurrentUser.USERID;
                    oCCROLEMENU.CREATEDON = DateTime.Now;
                    oDBContext.CCROLEMENUs.Add(oCCROLEMENU);
                    oDBContext.SaveChanges();
                }
                TempData["SuccessMsg"] = "Data Saved Successfully.";
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = "Data is not saved due to " + ExceptionMsg(ex);
            }
            return RedirectToAction("Index");
        }
        
    }
}

OBLContactCenter/Views/RoleMenuSetting/Index.cshtml
@{
    ViewBag.Title = "Role wise Menu Info";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">
    $(document).ready(function () {
        $(document).on("click", "#btnSearch", function () {
            $("#detailInfo").empty();
            var selectedValue = $("#ddlRoleMenu").val();
            var selectedMenu = $("#ddlMenu").val();
            if (selectedValue != '') {
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("GetRoleWiseMenuList", "RoleMenuSetting")',
                    dataType: 'html',
                    data: { id: selectedValue,MenuId: selectedMenu },
                    success: function (data) {
                        $('#detailInfo').html(data);
                    },
                    error: function (ex) {
                        alert('Failed to retrieve data.' + ex);
                    }
                });
            }
        });
    });

</script>


<div class="col-md-12 ">
    <div class="portlet box blue-ebonyclay">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-grid"></i>Role wise Menu Information
            </div>
        </div>
        <div class="portlet-body form">
            @if (TempData["SuccessMsg"] != null)
            {
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                    <strong><span class="fa fa-check"></span></strong>@TempData["SuccessMsg"].ToString()
                </div>
            }

            @if (TempData["ErrorMsg"] != null)
            {
                <div class="alert alert-danger alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                    <strong><span class="fa  fa-times"></span></strong>@TempData["ErrorMsg"].ToString()
                </div>
            }
            <div class="form-body">
                <div class="panel panel-info">

                    <div class="panel-body">
                        <div class="row panel-info">
                            <div class="form-group">
                                <label class="col-md-2 control-label">Role Name</label>
                                <div class="col-md-3">
                                    @Html.DropDownList("ddlRoleMenu", (IEnumerable<SelectListItem>)ViewBag.RoleList, "Select", new { @class = "form-control", id = "ddlRoleMenu" })
                                </div>
                                
                                <label class="col-md-2 control-label">Menu Name</label>
                                <div class="col-md-3">
                                    @Html.DropDownList("ddlMenu", (IEnumerable<SelectListItem>)ViewBag.MenuList, "Parent Menu", new { @class = "form-control", id = "ddlMenu" })
                                </div>
                                <button type="submit" class="btn green" name="btnName" id="btnSearch"><span class="fa fa-search"></span>Search</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div id="detailInfo">
                </div>
            </div>
        </div>
    </div>
</div>
</div>

OBLContactCenter/Views/RoleMenuSetting/_EditRolePartial.cshtml
@model OBLContactCenter.EFnClass.CCROLE
<script type="text/javascript">

    $("#chkIsActive").bootstrapSwitch();
    $("#chkIsAdmin").bootstrapSwitch();

    $("form").removeData("validator");
    $("form").removeData("unobtrusiveValidation");
    $.validator.unobtrusive.parse("form");

</script>
<div class="col-md-12 ">
    <div class="portlet box blue-hoki">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-grid"></i>Role Information
            </div>
        </div>
        <div class="portlet-body">

            @Html.AntiForgeryToken()
            @using (Html.BeginForm("InsertEditRole", "RoleSetting", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <div class="form-body">
                    <div id="hdnDiv" style="display: none;">
                        @Html.HiddenFor(m => m.ID);
                        @Html.HiddenFor(m => m.ISACTIVE);
                        @Html.HiddenFor(m => m.CREATEDBY);
                        @Html.HiddenFor(m => m.CREATEDON);
                        @Html.HiddenFor(m => m.MODIFIEDBY);
                        @Html.HiddenFor(m => m.MODIFIEDON);
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Role Name</label>
                        <div class="col-md-4">
                            @Html.TextBoxFor(m => m.ROLENAME, new { @class = "form-control", placeholder = "Enter Role Name" })
                            @*<input type="text" class="form-control" placeholder="Enter Employee ID/ User ID">*@
                        </div>
                        <div class="col-md-4">
                            @Html.ValidationMessageFor(m => m.ROLENAME, null, new { @class = "alert alert-danger display" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Is Admin ?</label>
                        <div class="col-md-4">
                            @Html.CheckBoxFor(m => m.ISADMIN, new { @name = "chkIsAdmin", id = "chkIsAdmin" })
                        </div>
                        <div class="col-md-4">

                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-md-3 control-label">Is Active ?</label>
                        <div class="col-md-4">
                            @Html.CheckBoxFor(m => m.ISACTIVE, new { @name = "chkIsActive", id = "chkIsActive" })
                        </div>
                        <div class="col-md-4">

                        </div>
                    </div>
                </div>
                <div class="form-actions">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            @if (Model.ID == 0)
                            {
                                <button type="submit" class="btn green" name="btnName" value="create" id="createBtn">Create</button>
                            }
                            else
                            {
                                <button type="submit" class="btn green" name="btnName" value="update" id="updateBtn">Update</button>
                            }
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

OBLContactCenter/Views/RoleMenuSetting/_RMenuAssignListPartial.cshtml
@model List<OBLContactCenter.Models.RoleMenu>

<div class="portlet box blue-ebonyclay">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-grid"></i>Role wise Menu Information
        </div>
    </div>

    <div class="portlet-body flip-scroll">
        @if (Model != null)
        {
            using (Html.BeginForm("SaveRoleMenuList", "RoleMenuSetting", FormMethod.Post, new { id = "frmRoleMenu", @class = "form-horizental" }))
            {
                var grid = new WebGrid(Model, rowsPerPage: 10, canPage: false, canSort: false);
            @grid.GetHtml(
                         tableStyle: "table table-bordered table-striped table-condensed flip-content",
                         headerStyle: "flip-content",

                         columns: new[]{
                             grid.Column(
                        header: "",
                        format:@<text>
            @if (item.IsAssigned == null)
                            {
<input name="chkSelect" type="checkbox" value="@item.ID" />
                            }
                            else
                            {
<input name="chkSelect" type="checkbox" value="@item.ID" checked="checked" />
                            }

            </text>
                    ),

                           grid.Column("MenuName",header: "NAME"),
                           //grid.Column(null,null,format:@<input type="hidden" name="MenuId" id="MenuId" value="@item.CCMENU2.ID" />),
            grid.Column(format:@<input type="hidden" name="RoleId" id="RoleId" value="@item.RoleId" />)
                            },
                                               mode: WebGridPagerModes.All
                                               );
               


            <div class="form-actions">
                <div class="row">
                    <div class="col-md-offset-6">

                        <button type="submit" class="btn green" name="btnName" value="update" id="btnSaveRoleMenu">Save</button>

                    </div>
                </div>
            </div>
            }
        }
        else
        {
            <div class="note note-warning">
                <h4 class="block"><span class="fa fa-warning"></span>No result found </h4>
            </div>
        }
    </div>
</div>

OBLContactCenter/Views/RoleMenuSetting/_RoleMenuPartial.cshtml
<script type="text/javascript">
    $(document).ready(function () {
        $("#ddlRoleMenu").change(function () {
            $("#detailInfo").empty();
            var selectedValue = $("#ddlRoleMenu").val();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetRoleWiseMenuList", "RoleMenuSetting")',
                dataType: 'json',
                data: { id: selectedValue },
                success: function (data) {
                    $('#detailInfo').html(data);
                },
                error: function (ex) {
                    alert('Failed to retrieve data.' + ex);
                }
            });
        });
    });

</script>
<div class="col-md-12 ">
    <div class="portlet box blue-ebonyclay">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-grid"></i>Role wise Menu Information
            </div>
        </div>
        <div class="portlet-body">
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">Role Name</label>
                    <div class="col-md-4">
                        @Html.DropDownList("ddlRoleMenu",(IEnumerable<SelectListItem>)ViewBag.RoleList, "Select", new { @class = "form-control", id = "ddlRoleMenu" })
                    </div>
                </div>
            </div>
            <div class="form-actions">
                <div class="row">
                    <div class="col-md-offset-3">
                            <button type="submit" class="btn green" name="btnName" value="create" id="SrchRMenuBtn">Search</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>