OBLContactCenter/Controllers/CRMController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OBLContactCenter.EFnClass;
using System.Data;
using System.Data.Entity.Validation;
using System.IO;
using System.Globalization;
namespace OBLContactCenter.Controllers
{
    [SessionExpire]
    public class CRMController : AppBaseController
    {


        public ActionResult Index()
        {
            oCurrentUser = (CCUSER)Session["User"];
            int enumDBType = 0;

            ViewBag.CallCatagoryList = oDBContext.CCCALLCATAGORies.Where(t => t.ISACTIVE).Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.NAME.ToString()
            });
            enumDBType = Convert.ToInt32(Enumaretion.DBEnumType.ActionType);
            ViewBag.ActionList = oDBContext.CCENUMERATIONs.Where(t => t.TYPE == enumDBType && t.ISACTIVE).Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.NAME.ToString()
            });

            var createList = oDBContext.CCMEMOMASTERs.Where(t => t.ISACTIVE && t.CREATEDBY == oCurrentUser.ID ).OrderByDescending(t => t.ID).ToList();
            Session["List"] = createList;

            return View(createList);
        }

        [HttpGet]
        public ActionResult SearchList(string ticktNo, string acCard, int? catagoryId, int? groupId, int? actionId, int? statusId, string from, string to, string custName, string contact, int? callTypeId)
        {
            oCurrentUser = (CCUSER)Session["User"];
            var list = oDBContext.CCMEMOMASTERs.Where(t => t.ISACTIVE && t.CREATEDBY == oCurrentUser.ID).ToList();
            if (!string.IsNullOrEmpty(ticktNo))
                list = list.Where(t => t.TICKETNO == ticktNo.Trim()).ToList();
            if (!string.IsNullOrEmpty(acCard))
                list = list.Where(t => (t.CUSTCARDNO != null && t.CUSTCARDNO.Contains(acCard)) || (t.CUSTACNO != null && t.CUSTACNO.Contains(acCard))).ToList();
            if (!string.IsNullOrEmpty(catagoryId.ToString()))
                list = list.Where(t => t.CALLCATEGORY == catagoryId).ToList();
            if (!string.IsNullOrEmpty(groupId.ToString()))
                list = list.Where(t => t.ASSIGNGROUP == groupId).ToList();
            if (!string.IsNullOrEmpty(actionId.ToString()))
                list = list.Where(t => t.LASTACTIONTYPE == actionId).ToList();
            if (!string.IsNullOrEmpty(from))
            {
                var fromDate = DateTime.ParseExact(from, "dd/MM/yyyy", CultureInfo.InvariantCulture);
                list = list.Where(t => t.CREATEDON >= fromDate).ToList();
            }
            if (!string.IsNullOrEmpty(to))
            {
                var toDate = DateTime.ParseExact(to, "dd/MM/yyyy", CultureInfo.InvariantCulture);
                list = list.Where(t => t.CREATEDON <= toDate.AddHours(23).AddMinutes(59).AddSeconds(59)).ToList();
            }
            if (!string.IsNullOrEmpty(custName.Trim()))
            {
                list = list.Where(t => t.CUSTOMERNAME.Contains(custName)).ToList();
            }
            if (!string.IsNullOrEmpty(contact.Trim()))
            {
                list = list.Where(t => t.CUSTOMERCONTACT.Contains(contact)).ToList();
            }
            if (!string.IsNullOrEmpty(callTypeId.ToString()))
            {
                list = list.Where(t => t.CALLTYPE == callTypeId.Value).ToList();
            }
            return PartialView("_createListPartial", list);
        }

        public ActionResult CreateMemo()
        {
            oCurrentUser = (CCUSER)Session["User"];
            int enumDBType = 0;
            enumDBType = Convert.ToInt32(Enumaretion.DBEnumType.FormType);
            long InboundType = oDBContext.CCENUMERATIONs.FirstOrDefault(x => x.TYPE == enumDBType && x.NAME.ToLower().Contains("inbound") && x.ISACTIVE == true).ID;

            CCMEMOMASTER oCCMEMOMASTER = new CCMEMOMASTER();

            oCCMEMOMASTER.TICKETNO = DateTime.Now.ToString("yyMMddhhmmssfff");

            enumDBType = Convert.ToInt32(Enumaretion.DBEnumType.StatusType);
            ViewBag.StatusList = oDBContext.CCENUMERATIONs.Where(t => t.TYPE == enumDBType && t.ISACTIVE).Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.VALUE.ToString(),
                Text = x.NAME.ToString()
            });

            enumDBType = Convert.ToInt32(Enumaretion.DBEnumType.FormType);
            ViewBag.MemoTypeList = oDBContext.CCENUMERATIONs.Where(t => t.TYPE == enumDBType && t.ISACTIVE).Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.NAME.ToString()
            });
            enumDBType = Convert.ToInt32(Enumaretion.DBEnumType.PriorityType);
            ViewBag.PriorityList = oDBContext.CCENUMERATIONs.Where(t => t.TYPE == enumDBType && t.ISACTIVE).Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.NAME.ToString()
            });

            ViewBag.CallCatagoryList = oDBContext.CCCALLCATAGORies.Where(t => t.ISACTIVE).Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.NAME.ToString()
            });

            enumDBType = Convert.ToInt32(Enumaretion.DBEnumType.SourceType);
            ViewBag.SourceList = oDBContext.CCENUMERATIONs.Where(t => t.TYPE == enumDBType && t.ISACTIVE).Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.NAME.ToString()
            });
            enumDBType = Convert.ToInt32(Enumaretion.DBEnumType.ProductType);
            ViewBag.ProductList = oDBContext.CCENUMERATIONs.Where(t => t.TYPE == enumDBType && t.ISACTIVE).Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.NAME.ToString()
            });
            enumDBType = Convert.ToInt32(Enumaretion.DBEnumType.ActionType);
            //ViewBag.ActionList = oDBContext.CCENUMERATIONs.Where(t => t.CCACTIONMAPs.Where(p => p.ROLEID == oCurrentUser.EMPLOYEEROLEID && p.MEMOTYPEID == InboundType) != null && t.ISACTIVE).Select(x => x).ToList().Select(x => new SelectListItem
            ViewBag.ActionList = oDBContext.CCACTIONMAPs.Where(p => p.ROLEID == oCurrentUser.EMPLOYEEROLEID && p.MEMOTYPEID == InboundType && p.ISACTIVE == true).Select(x => x.CCENUMERATION).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.NAME.ToString()
            });
            oCCMEMOMASTER.ASSIGNGROUP = oCurrentUser.GROUPID;
            ViewBag.AssignGroupList = oDBContext.CCGROUPs.Where(t =>t.ID == oCurrentUser.GROUPID && t.ISACTIVE).Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.GROUPNAME.ToString(),
                Selected = true,
            });
            oCCMEMOMASTER.ISOPEN = true;
            return PartialView("_createFrmPartial", oCCMEMOMASTER);
        }

        public ActionResult EditMemo(int id)
        {
            oCurrentUser = (CCUSER)Session["User"];
            int enumDBType = 0;
            CCMEMOMASTER oCCMEMOMASTER = new CCMEMOMASTER();

            oCCMEMOMASTER.TICKETNO = DateTime.Now.ToString("yyMMddhhmmssfff");
            enumDBType = Convert.ToInt32(Enumaretion.DBEnumType.StatusType);
            ViewBag.StatusList = oDBContext.CCENUMERATIONs.Where(t => t.TYPE == enumDBType && t.ISACTIVE).Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.VALUE.ToString(),
                Text = x.NAME.ToString()
            });

            enumDBType = Convert.ToInt32(Enumaretion.DBEnumType.FormType);
            ViewBag.MemoTypeList = oDBContext.CCENUMERATIONs.Where(t => t.TYPE == enumDBType && t.ISACTIVE).Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.NAME.ToString()
            });
            enumDBType = Convert.ToInt32(Enumaretion.DBEnumType.PriorityType);
            ViewBag.PriorityList = oDBContext.CCENUMERATIONs.Where(t => t.TYPE == enumDBType && t.ISACTIVE).Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.NAME.ToString()
            });

            ViewBag.CallCatagoryList = oDBContext.CCCALLCATAGORies.Where(t => t.ISACTIVE).Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.NAME.ToString()
            });

            enumDBType = Convert.ToInt32(Enumaretion.DBEnumType.SourceType);
            ViewBag.SourceList = oDBContext.CCENUMERATIONs.Where(t => t.TYPE == enumDBType && t.ISACTIVE).Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.NAME.ToString()
            });
            enumDBType = Convert.ToInt32(Enumaretion.DBEnumType.ProductType);
            ViewBag.ProductList = oDBContext.CCENUMERATIONs.Where(t => t.TYPE == enumDBType && t.ISACTIVE).Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.NAME.ToString()
            });
            enumDBType = Convert.ToInt32(Enumaretion.DBEnumType.ActionType);
            ViewBag.ActionList = oDBContext.CCACTIONMAPs.Where(p => p.ROLEID == oCurrentUser.EMPLOYEEROLEID && p.MEMOTYPEID == oCCMEMOMASTER.MEMOTYPE && p.ISACTIVE == true).Select(x => x.CCENUMERATION).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),

OBLContactCenter/Controllers/SignInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OBLContactCenter.EFnClass;
using OBLContactCenter.Models;
using System.Web.Security;

namespace OBLContactCenter.Controllers
{
    public class SignInController : AppBaseController
    {
        //
        // GET: /SignIn/
        CCUSER oCCUSER = null;

        [AllowAnonymous]
        [EventLog(EventType="Sys",customeEventName="Login")]
        public ActionResult Index()
        {
            
            
            Session.Clear();
            return View();
        }

        [AllowAnonymous]
        public ActionResult SignIn(LogIn objSignIn)
        {
            if (ModelState.IsValid)
            {
                if (Membership.ValidateUser(objSignIn.USERID, objSignIn.USERPASSWORD))
                {
                    oCCUSER = oDBContext.CCUSERs.FirstOrDefault(t => t.USERID == objSignIn.USERID && t.USERPASSWORD == objSignIn.USERPASSWORD);
                    Session["User"] = oCCUSER;
                    Session["UserRole"] = oCCUSER.CCROLE.ROLENAME;
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    TempData["SignMsg"] = "Invalid User ID / Password";
                    return View("Index");
                }
                //oCCUSER = oDBContext.CCUSERs.FirstOrDefault(t => t.USERID == objSignIn.USERID && t.USERPASSWORD == objSignIn.USERPASSWORD);
                //if (oCCUSER != null)
                //{
                //    Session["User"] = oCCUSER;
                //    Session["UserRole"] = oCCUSER.CCROLE.ROLENAME;
                //    Roles.AddUserToRole(oCCUSER.USERID, oCCUSER.CCROLE.ROLENAME);
                //    return RedirectToAction("Index", "Home");
                //}
                //else
                //{
                //    TempData["SignMsg"] = "Invalid User ID / Password";
                //    return View("Index");
                //}
            }

            return View("Index");
        }
        public ActionResult LogOut(string Msg)
        {
            //TempData["SignMsg"] = RouteData.Values["Msg"];
            
            Session.Clear();
            return View("Index");
        }

        public ActionResult NotAuthorized()
        {
            TempData["SignMsg"] = "Not Authorized. Please Sign in again...";
            Session.Clear();
            return View("Index");
        }

    }
}

OBLContactCenter/Views/Shared/Copy of _Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

OBLContactCenter/Views/Shared/_HeaderPartial.cshtml
@model OBLContactCenter.Models.UserInfo
<script type="text/javascript">
    $(document).ready(function () {
        $('#ModDetailInfo').on('hidden.bs.modal', function () {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("CloseModalTaskEnd", "CRMTask")',
                data: {},
                success: function (states) {
                },
                error: function (ex) {
                    alert(ex);
                }
            });
        });

        $('.notifyTaskCRM').click(function () {
            var url = '@Url.Action("EditTaskMemo", "CRMTask")'; // the url to the controller
            var id = $(this).attr('data-id');
            $.get(url + '/' + id, function (data) {
                $('#ModDetailInfo .modal-body').html(data);
                $('#ModDetailInfo').modal('show');
                $.validator.unobtrusive.parse($('.modal-body'));
            });
        });
    });

</script>
<div class="top-menu">
    <ul class="nav navbar-nav pull-right">
        <!-- BEGIN NOTIFICATION DROPDOWN -->
        <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->

        @*<li class="dropdown dropdown-extended dropdown-notification" id="header_notification_bar">
            <a href="javascript:;" class="dropdown-toggle" id="addTicket">
                <i class="icon-tag"></i>
            </a>
        </li>*@
        <li class="dropdown dropdown-extended dropdown-notification" id="header_notification_bar">
            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                <i class="icon-pin"></i>
                <span class="badge badge-danger">
                    @Model.PriorityTaskList.Count.ToString()
                </span>
            </a>
            <ul class="dropdown-menu">
                <li class="external">
                    <h3><span class="bold">@Model.PriorityTaskList.Count.ToString() pending</span> notifications</h3>
                    <a href="@Url.Action("Index", "CRMTask")">View all</a>
                </li>
                <li>
                    <ul class="dropdown-menu-list scroller" style="height: 150px;" data-handle-color="#637283">
                        @foreach (var item in Model.PriorityTaskList)
                        {
                            <li>
                                <a href="javascript:;" class="notifyTaskCRM" data-id="@item.ID">
                                    <span class="time">@item.MODIFIEDON</span>
                                    <span class="details">
                                        <span class="label label-sm label-icon label-danger">

                                            <i class="fa fa-bolt"></i>
                                        </span>
                                        @item.REQUESTDETAILS
                                    </span>
                                </a>
                            </li>
                        }

                    </ul>
                </li>
            </ul>
        </li>
        <li class="dropdown dropdown-extended dropdown-notification" id="header_notification_bar">
            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                <i class="icon-bell"></i>
                <span class="badge badge-danger">
                    @Model.PendingTaskList.Count.ToString()
                </span>
            </a>
            <ul class="dropdown-menu">
                <li class="external">
                    <h3><span class="bold">@Model.PendingTaskList.Count.ToString() pending</span> notifications</h3>
                    <a href="@Url.Action("Index", "CRMTask")">View all</a>
                </li>
                <li>
                    <ul class="dropdown-menu-list scroller" style="height: 150px;" data-handle-color="#637283">
                        @foreach (var item in Model.PendingTaskList)
                        {
                            <li>
                                <a href="javascript:;" class="notifyTaskCRM" data-id="@item.ID">
                                    <span class="time">@item.MODIFIEDON</span>
                                    <span class="details">
                                        <span class="label label-sm label-icon label-danger">

                                            <i class="fa fa-bolt"></i>
                                        </span>
                                        @item.REQUESTDETAILS
                                    </span>
                                </a>
                            </li>
                        }

                    </ul>
                </li>
            </ul>
        </li>

        <!-- END NOTIFICATION DROPDOWN -->
        <!-- BEGIN USER LOGIN DROPDOWN -->
        <li class="dropdown dropdown-user">
            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                @if (string.IsNullOrEmpty(Model.IMAGEPATH))
                {
                    <img alt="" class="img-circle" src="~/Content/UserImage/avatar.png" />
                }
                else
                {
                    <img alt="" class="img-circle" src="~/Content/UserImage/@Model.IMAGEPATH" />
                }
                <span class="username username-hide-on-mobile">
                    @Model.USERID
                </span>
                <i class="fa fa-angle-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-menu-default">
                <li>
                    <a href="@Url.Action("Profile", "UserSetting", new { Length = @Model.ID.ToString() })">
                        <i class="icon-user"></i>My Profile
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="@Url.Action("ChangePasswordProfile", "UserSetting", new { Id = @Model.ID.ToString() })">
                        <i class="icon-key"></i>Change Password
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="@Url.Action("LogOut", "SignIn")">
                        <i class="icon-logout"></i>Log Out
                    </a>
                </li>
            </ul>
        </li>
        <!-- END USER LOGIN DROPDOWN -->

    </ul>

</div>

<div class="fixed-action-btn" style="bottom: 45px; right: 24px; " id="makeCRM" data-url="@Url.Action("CreateMemo", "CRM")">
    <a class="btn-floating btn-circle">
        <i class="fa fa-plus"></i>
    </a>
</div>

OBLContactCenter/Views/Shared/_TickerPartial.cshtml
@model OBLContactCenter.Models.Dashboard
<link href="~/Content/liScroll.css" rel="stylesheet" />
<script src="~/Scripts/liScroll.js"></script>
<script type="text/javascript">

    $(document).ready(function () {
        $("ul#tickerNews").liScroll();
    });
</script>

@if (Model.NewsTicker != null)
{
    <div class="note note-info">
        <ul id="tickerNews" style="font-size: 16px;">
            @foreach (var item in Model.NewsTicker)
            {
                <li><span> :: </span> <b>@item.NAME</b> :  @item.VALUE <span class="fa fa-calendar"></span>@item.CREATEDON <span> :: </span></li> 
            }
        </ul>
    </div>
}

OBLContactCenter/Views/Shared/_UserMenuPartial.cshtml
@model List<CCROLEMENU>

<div class="page-sidebar navbar-collapse collapse">
    <ul class="page-sidebar-menu " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">

        <li class="sidebar-toggler-wrapper">

            <div class="sidebar-toggler">
            </div>

        </li>
        <li class="sidebar-search-wrapper">
            <div class="sidebar-search">
                <div class="input-group">
                    <input type="text" class="form-control" id="srchTxt" placeholder="Ticket/Name/Contact/Card/Ac No" style="color: #fff;">
                    <span class="input-group-btn">
                        <a class="btn submit" id="srchBtn" data-url="@Url.Action("SrchTicket", "Home")" ><i class="icon-magnifier"></i></a>
                    </span>
                </div>

            </div>
            <!-- END RESPONSIVE QUICK SEARCH FORM -->
        </li>
        @foreach (var item in Model)
        {
            @Html.ParentMenuItem(item.CCMENU.NAME, item.CCMENU.CCMENU1.OrderBy(t => t.ORDERNO).ToList(), iconClass: item.CCMENU.ICONTEXT);
        }

    </ul>

</div>