OBLContactCenter/Controllers/CallCatTypeSettingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OBLContactCenter.EFnClass;
using System.Data;
using OBLContactCenter.Models;
using System.Data.Entity;
namespace OBLContactCenter.Controllers
{
    [SessionExpire]
    public class CallCatTypeSettingController : AppBaseController
    {

        CCCALLCATAGORY oCCCALLCATAGORY = null;
        CCCALLTYPE oCCCALLTYPE = null;

        public ActionResult Index()
        {
            CALLCATAGORYTYPE CallCatTypeList = new CALLCATAGORYTYPE();

            CallCatTypeList.CallCatagoryList = oDBContext.CCCALLCATAGORies.ToList();
            CallCatTypeList.CallTypeList = oDBContext.CCCALLTYPEs.ToList();
            CallCatTypeList.SelectedList = 1;

            ViewBag.CallCatagoryList = oDBContext.CCCALLCATAGORies.Where(t => t.ISACTIVE).Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.NAME.ToString()
            });

            return View(CallCatTypeList);
        }

        [HttpGet]
        public ActionResult SearchTypeList(int? catagoryId, int? page)
        {
            //oCurrentUser = (CCUSER)Session["User"];
            var list = oDBContext.CCCALLTYPEs.Where(t => t.ISACTIVE ).ToList();
            if (!string.IsNullOrEmpty(catagoryId.ToString()))
                list = list.Where(t => t.CATAGORYID == catagoryId).ToList();

            return PartialView("_TypeListPartial", list);
        }

        [HttpGet]
        public ActionResult CreateCategory()
        {
            oCCCALLCATAGORY = new CCCALLCATAGORY();
            oCCCALLCATAGORY.ISACTIVE = true;

            return PartialView("_EditCatagoryPartial", oCCCALLCATAGORY);
        }

        [HttpGet]
        public ActionResult EditCategory(int id)
        {

            oCCCALLCATAGORY = oDBContext.CCCALLCATAGORies.FirstOrDefault(t => t.ID == id);

            return PartialView("_EditCatagoryPartial", oCCCALLCATAGORY);
        }

        [HttpPost]
        public ActionResult InsertEditCategory(CCCALLCATAGORY oCCCALLCATAGORY, string btnName)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            try
            {
                if (ModelState.IsValid)
                {
                    oCurrentUser = (CCUSER)Session["User"];
                    switch (btnName)
                    {
                        case "create":
                            oCCCALLCATAGORY.ISACTIVE = true;
                            oCCCALLCATAGORY.CREATEDBY = oCurrentUser.ID;
                            oCCCALLCATAGORY.CREATEDON = DateTime.Now;

                            oDBContext.CCCALLCATAGORies.Add(oCCCALLCATAGORY);
                            oDBContext.SaveChanges();
                            TempData["SuccessMsg"] = "Data Saved Successfully.";
                            break;
                        case "update":
                            oCCCALLCATAGORY.MODIFIEDBY = oCurrentUser.ID;
                            oCCCALLCATAGORY.MODIFIEDON = DateTime.Now;
                            oDBContext.Entry(oCCCALLCATAGORY).State = EntityState.Modified;
                            oDBContext.SaveChanges();
                            TempData["SuccessMsg"] = "Data Updated Successfully.";
                            break;
                    }

                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = "Data is not saved due to " + ExceptionMsg(ex);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult CreateType()
        {
            oCCCALLTYPE = new CCCALLTYPE();
            oCCCALLTYPE.ISACTIVE = true;

            ViewBag.CatList = oDBContext.CCCALLCATAGORies.Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.NAME.ToString()
            });


            return PartialView("_EditTypePartial", oCCCALLTYPE);
        }

        [HttpGet]
        public ActionResult EditType(int id)
        {
            ViewBag.CatList = oDBContext.CCCALLCATAGORies.Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.NAME.ToString()
            });

            oCCCALLTYPE = oDBContext.CCCALLTYPEs.FirstOrDefault(t => t.ID == id);

            return PartialView("_EditTypePartial", oCCCALLTYPE);
        }

        [HttpPost]
        public ActionResult InsertEditType(CCCALLTYPE oCCCALLTYPE, string btnName)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            try
            {
                if (ModelState.IsValid)
                {
                    oCurrentUser = (CCUSER)Session["User"];
                    switch (btnName)
                    {
                        case "create":
                            oCCCALLTYPE.ISACTIVE = true;
                            oCCCALLTYPE.CREATEDBY = oCurrentUser.ID;
                            oCCCALLTYPE.CREATEDON = DateTime.Now;

                            oDBContext.CCCALLTYPEs.Add(oCCCALLTYPE);
                            oDBContext.SaveChanges();
                            TempData["SuccessMsg"] = "Data Saved Successfully.";
                            break;
                        case "update":
                            oCCCALLTYPE.MODIFIEDBY = oCurrentUser.ID;
                            oCCCALLTYPE.MODIFIEDON = DateTime.Now;
                            oDBContext.Entry(oCCCALLTYPE).State = EntityState.Modified;
                            oDBContext.SaveChanges();
                            TempData["SuccessMsg"] = "Data Updated Successfully.";
                            break;
                    }

                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = "Data is not saved due to " + ExceptionMsg(ex);
            }
            return RedirectToAction("Index");
        }


    }
}

OBLContactCenter/Views/CallCatTypeSetting/Index.cshtml
@model OBLContactCenter.Models.CALLCATAGORYTYPE
@{
    ViewBag.Title = "Category & Type Info";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">

    $(document).ready(function () {
        $('#taskSearch').click(function () {
            var actionurl = '@Url.Action("SearchTypeList", "CallCatTypeSetting")'; // the url to the controller
            var catagoryId = $('#srchCatagoryId').val();
            $.ajax({
                cache: false,
                type: "GET",
                url: actionurl,
                data: { "catagoryId": catagoryId },
                success: function (data) {
                    $('#TypegridList').html(data);
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Failed to load Information');
                }
            });
        });
    });
</script>

<div class="col-md-12 ">


    @if (TempData["SuccessMsg"] != null)
    {
        <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
            <strong><span class="fa fa-check"></span></strong>@TempData["SuccessMsg"].ToString()
        </div>
    }

    @if (TempData["ErrorMsg"] != null)
    {
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
            <strong><span class="fa  fa-times"></span></strong>@TempData["ErrorMsg"].ToString()
        </div>
    }



    <div id="CatgridList">
        @Html.Partial("_CatagoryListPartial", Model.CallCatagoryList)
    </div>
    <div class="portlet box blue-ebonyclay">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-grid"></i>Call Type Information
            </div>
            <div class="tools">
                <button class="btn green" id="createType" data-url="@Url.Action("CreateType", "CallCatTypeSetting")">Create <i class="fa fa-plus"></i></button>
            </div>
        </div>

        <div class="portlet-body flip-scroll">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <td>
                            <label class="control-label">Catagory</label>
                        </td>
                        <td>
                            <label class="control-label">Action</label>
                        </td>
                    </tr>
                </thead>
                <tr>

                    <td>
                        @Html.DropDownList("srchCatagoryId", (IEnumerable<SelectListItem>)ViewBag.CallCatagoryList, "All", new { @class = "form-control", id = "srchCatagoryId" })

                    </td>
                    <td>
                        <button class="btn green" id="taskSearch">Search <i class="fa fa-search"></i></button>
                    </td>

                </tr>
            </table>

            @Html.Partial("_TypeListPartial", Model.CallTypeList)

        </div>
    </div>
    <div id="userInfo">
    </div>
    <!-- END FORM-->
</div>
<div class="modal fade bs-modal-lg" id="DetailInfo" tabindex="-1" role="basic" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn default">Cancel</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

OBLContactCenter/Views/CallCatTypeSetting/_CatagoryListPartial.cshtml
@model List<OBLContactCenter.EFnClass.CCCALLCATAGORY>

<div class="portlet box blue-ebonyclay">
    <div class="portlet-title">
       <div class="caption">
                <i class="fa fa-grid"></i>Call Category Information
            </div>
        <div class="tools">
            <button class="btn green" id="createCat" data-url="@Url.Action("CreateCategory", "CallCatTypeSetting")">Create <i class="fa fa-plus"></i></button>
        </div>
    </div>
    <div class="portlet-body flip-scroll">
        @if (Model != null)
        {
            var grid = new WebGrid(Model, rowsPerPage: 10, canPage: true, canSort: false, ajaxUpdateContainerId: "CatgridList");
            grid.PagerList(WebGridPagerModes.All, paginationStyle: "Pagination");


            @grid.GetHtml(
             tableStyle: "table table-bordered table-striped table-condensed flip-content",
             headerStyle: "flip-content",
             columns: new[]{
               grid.Column(header: "Category",format:@<text><a class="editCat" data-id="@item.ID" data-url="@Url.Action("EditCategory", "CallCatTypeSetting")">@item.NAME</a></text>),
               grid.Column("REMARKS",header: "Remarks"),
               grid.Column("ISACTIVE", "Status",format: (item) => (item.ISACTIVE) ? Html.Raw("<span class='fa fa-check-square-o'></span>") :
                                                                                        Html.Raw("<span class='fa fa-times'></span>"))
                @*grid.Column("", "Action", format: @<button class="btn red editCat" data-id="@item.ID" data-url="@Url.Action("EditCategory", "CallCatTypeSetting")">Edit <i class="fa fa-edit"></i></button>)*@

                },
                          mode: WebGridPagerModes.All
                          );
        }
        else
        {
            <div class="note note-warning">
                <h4 class="block"><span class="fa fa-warning"></span>No result found </h4>
            </div>
        }
    </div>
</div>

OBLContactCenter/Views/CallCatTypeSetting/_EditCatagoryPartial.cshtml
@model OBLContactCenter.EFnClass.CCCALLCATAGORY
<script type="text/javascript">

    
    $("#chkIsActive").bootstrapSwitch();

    $("form").removeData("validator");
    $("form").removeData("unobtrusiveValidation");
    $.validator.unobtrusive.parse("form");

</script>
<div class="col-md-12 ">
    <div class="portlet box blue-ebonyclay">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-grid"></i> Call Category Information
            </div>

        </div>
        <div class="portlet-body">

            @Html.AntiForgeryToken()
            @using (Html.BeginForm("InsertEditCategory", "CallCatTypeSetting", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <div class="form-body">
                    <div id="hdnDiv" style="display: none;">
                        @Html.HiddenFor(m => m.ID);
                        
                        @Html.HiddenFor(m => m.CREATEDBY);
                        @Html.HiddenFor(m => m.CREATEDON);
                        @Html.HiddenFor(m => m.MODIFIEDBY);
                        @Html.HiddenFor(m => m.MODIFIEDON);
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Category Name</label>
                        <div class="col-md-4">
                            @Html.TextBoxFor(m => m.NAME, new { @class = "form-control", placeholder = "Enter Category Name" })
                            
                        </div>
                        <div class="col-md-4">
                            @Html.ValidationMessageFor(m => m.NAME, null, new { @class = "alert alert-danger display" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Remarks</label>
                        <div class="col-md-4">
                            @Html.TextAreaFor(m => m.REMARKS, new { @class = "form-control"})
                            
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Is Active ?</label>
                        <div class="col-md-4">
                            @Html.CheckBoxFor(m => m.ISACTIVE, new { @name = "chkIsActive", id = "chkIsActive" })
                        </div>
                        <div class="col-md-4">

                        </div>
                    </div>
                </div>
                <div class="form-actions">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            @if (Model.ID == 0)
                            {
                                <button type="submit" class="btn green" name="btnName" value="create" id="createBtn">Create</button>
                            }
                            else
                            {
                                <button type="submit" class="btn green" name="btnName" value="update" id="updateBtn">Update</button>
                            }
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

OBLContactCenter/Views/CallCatTypeSetting/_EditTypePartial.cshtml
@model OBLContactCenter.EFnClass.CCCALLTYPE
<script type="text/javascript">

    
    $("#chkIsActive").bootstrapSwitch();

    $("form").removeData("validator");
    $("form").removeData("unobtrusiveValidation");
    $.validator.unobtrusive.parse("form");

</script>
<div class="col-md-12 ">
    <div class="portlet box blue-ebonyclay">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-grid"></i>Call Type Information
            </div>

        </div>
        <div class="portlet-body">

            @Html.AntiForgeryToken()
            @using (Html.BeginForm("InsertEditType", "CallCatTypeSetting", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <div class="form-body">
                    <div id="hdnDiv" style="display: none;">
                        @Html.HiddenFor(m => m.ID);
                        
                        @Html.HiddenFor(m => m.CREATEDBY);
                        @Html.HiddenFor(m => m.CREATEDON);
                        @Html.HiddenFor(m => m.MODIFIEDBY);
                        @Html.HiddenFor(m => m.MODIFIEDON);
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Call Type Name</label>
                        <div class="col-md-4">
                            @Html.TextBoxFor(m => m.TYPENAME, new { @class = "form-control", placeholder = "Enter Call Type Name" })
                            
                        </div>
                        <div class="col-md-4">
                            @Html.ValidationMessageFor(m => m.TYPENAME, null, new { @class = "alert alert-danger display" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Call Category</label>
                        <div class="col-md-4">
                            @Html.DropDownListFor(m => m.CATAGORYID, (IEnumerable<SelectListItem>)ViewBag.CatList, "Select Call Catagory", new { @class = "form-control" })

                        </div>
                        <div class="col-md-4">
                            @Html.ValidationMessageFor(m => m.CATAGORYID, null, new { @class = "alert alert-danger display" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Remarks</label>
                        <div class="col-md-4">
                            @Html.TextAreaFor(m => m.REMARKS, new { @class = "form-control"})
                            
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Is Active ?</label>
                        <div class="col-md-4">
                            @Html.CheckBoxFor(m => m.ISACTIVE, new { @name = "chkIsActive", id = "chkIsActive" })
                        </div>
                        <div class="col-md-4">

                        </div>
                    </div>
                </div>
                <div class="form-actions">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            @if (Model.ID == 0)
                            {
                                <button type="submit" class="btn green" name="btnName" value="create" id="createBtn">Create</button>
                            }
                            else
                            {
                                <button type="submit" class="btn green" name="btnName" value="update" id="updateBtn">Update</button>
                            }
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

OBLContactCenter/Views/CallCatTypeSetting/_TypeListPartial.cshtml
@model List<OBLContactCenter.EFnClass.CCCALLTYPE>


<div id="TypegridList">
    @if (Model != null)
    {
        var grid = new WebGrid(Model, rowsPerPage: 10, canPage: true, canSort: false, ajaxUpdateContainerId: "TypegridList");



        @grid.Table(
             tableStyle: "table table-bordered table-striped table-condensed flip-content",
             headerStyle: "flip-content",
             columns: new[]{
               grid.Column(header: "Category",format:@<text><a class="editType" data-id="@item.ID" data-url="@Url.Action("EditType", "CallCatTypeSetting")">@item.TYPENAME</a></text>),
               grid.Column("CCCALLCATAGORY.NAME",header: "Call Catagory"),
               //grid.Column("TYPENAME",header: "Call Type"),
               grid.Column("REMARKS",header: "Remarks"),
               grid.Column("ISACTIVE", "Status",format: (item) => (item.ISACTIVE) ? Html.Raw("<span class='fa fa-check-square-o'></span>") :
                                                                                        Html.Raw("<span class='fa fa-times'></span>"))
                @*grid.Column("", "Action", format: @<button class="btn red editType" data-id="@item.ID" data-url="@Url.Action("EditType", "CallCatTypeSetting")">Edit <i class="fa fa-edit"></i></button>)*@

                }
                      );
        <div class="row">
            <div class="col-sm-6">
                @grid.PagerList(mode: WebGridPagerModes.All, paginationStyle: "pagination")
            </div>
        </div>
    }
    else
    {
        <div class="note note-warning">
            <h4 class="block"><span class="fa fa-warning"></span>No result found </h4>
        </div>
    }
</div>