OBLContactCenter/Controllers/RoleActionSettingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OBLContactCenter.EFnClass;
using System.Data;
using OBLContactCenter.Models;
namespace OBLContactCenter.Controllers
{
    [SessionExpire]
    
    public class RoleActionSettingController : AppBaseController
    {
        
        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Index()
        {
            int enumDBType = 0;
            enumDBType = Convert.ToInt32(Enumaretion.DBEnumType.FormType);
            ViewBag.RoleList = oDBContext.CCROLEs.Where(t => t.ISACTIVE).Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.ROLENAME.ToString()
            });

            ViewBag.MemoTypeList = oDBContext.CCENUMERATIONs.Where(t => t.TYPE == enumDBType && t.ISACTIVE).Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.NAME.ToString()
            });

            return View();
        }


        
        [HttpGet]
        public ActionResult GetRoleWiseActionList(int RoleId, int MTypeId)
        {
            int enumDBType =0;
            enumDBType = Convert.ToInt32(Enumaretion.DBEnumType.FormType);
            var MTypeList = oDBContext.CCENUMERATIONs.Where(t => t.TYPE == enumDBType && t.ISACTIVE).Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.NAME.ToString()
            }).ToList();
            enumDBType = Convert.ToInt32(Enumaretion.DBEnumType.ActionType);
            var roleActionItemList = oDBContext.CCENUMERATIONs.Where(t => t.ISACTIVE && t.TYPE == enumDBType).Select(t => new RoleAction
            {
                ActionID=t.ID,
                ActionName=t.NAME,
                RoleId = RoleId,
                RoleName = t.CCACTIONMAPs.FirstOrDefault(x => x.ROLEID == RoleId && x.MEMOTYPEID ==MTypeId).CCROLE.ROLENAME,
                IsAssigned = t.CCACTIONMAPs.FirstOrDefault(x => x.ROLEID == RoleId && x.MEMOTYPEID == MTypeId).ISACTIVE,
                MemoTypeID = MTypeId

            }).ToList();
            return PartialView("_RolewiseActionListPartial", roleActionItemList);
        }


        public ActionResult SaveRoleActionList(FormCollection frmCollection)
        {
            try
            {
                oCurrentUser = (CCUSER)Session["User"];
                var roleId = frmCollection["RoleId"].ToList()[0].ToString();
                var MemoTypeId = frmCollection["MemoTypeID"].ToList()[0].ToString();

                oDBContext.Database.ExecuteSqlCommand("Delete from CCACTIONMAP where ROLEID = {0} AND MEMOTYPEID = {1} ", roleId, MemoTypeId);
                oDBContext.SaveChanges();

                var selectedRoleMenuId = frmCollection.GetValues("chkSelect").ToList();
                foreach (string oActionId in selectedRoleMenuId)
                {
                    CCACTIONMAP oCCACTIONMAP = new CCACTIONMAP();
                    oCCACTIONMAP.ROLEID = Convert.ToInt32(roleId);
                    oCCACTIONMAP.MEMOTYPEID = Convert.ToInt32(MemoTypeId);
                    oCCACTIONMAP.ACTIONID = Convert.ToInt32(oActionId);
                    oCCACTIONMAP.ISACTIVE = true;
                    oCCACTIONMAP.CREATEDBY = oCurrentUser.USERID;
                    oCCACTIONMAP.CREATEDON = DateTime.Now;
                    oDBContext.CCACTIONMAPs.Add(oCCACTIONMAP);
                    oDBContext.SaveChanges();
                }
                TempData["SuccessMsg"] = "Data Saved Successfully.";
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = "Data is not saved due to " + ExceptionMsg(ex);
            }
            return RedirectToAction("Index");
        }
        
    }
}

OBLContactCenter/Views/RoleActionSetting/Index.cshtml
@{
    ViewBag.Title = "Role wise Action Info";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">
    $(document).ready(function () {
        $("#btnSearch").click(function () {
            $("#detailInfo").empty();
            var selectedValue = $("#ddlRoleAction").val();
            var selectedMType = $("#ddlMemoType").val();
            if (selectedValue != '' && selectedMType != '') {
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("GetRoleWiseActionList", "RoleActionSetting")',
                    dataType: 'html',
                    data: { RoleId: selectedValue ,MTypeId: selectedMType},
                    success: function (data) {
                        $('#detailInfo').html(data);
                    },
                    error: function (ex) {
                        alert('Failed to retrieve data.' + ex);
                    }
                });
            }
        });
    });

</script>


<div class="col-md-12 ">
    <div class="portlet box blue-ebonyclay">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-grid"></i>Role wise Action Information
            </div>
        </div>
        <div class="portlet-body form">
            @if (TempData["SuccessMsg"] != null)
            {
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                    <strong><span class="fa fa-check"></span></strong>@TempData["SuccessMsg"].ToString()
                </div>
            }

            @if (TempData["ErrorMsg"] != null)
            {
                <div class="alert alert-danger alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                    <strong><span class="fa  fa-times"></span></strong>@TempData["ErrorMsg"].ToString()
                </div>
            }
            <div class="form-body">
                <div class="panel panel-info">

                    <div class="panel-body">
                        <div class="row panel-info">
                            <div class="form-group">
                                <label class="col-md-2 control-label">Role Name</label>
                                <div class="col-md-3">
                                    @Html.DropDownList("ddlRoleAction", (IEnumerable<SelectListItem>)ViewBag.RoleList, "Select", new { @class = "form-control", id = "ddlRoleAction" })
                                </div>
                                <label class="col-md-2 control-label">Memo Type</label>
                                <div class="col-md-3">
                                    @Html.DropDownList("ddlMemoType", (IEnumerable<SelectListItem>)ViewBag.MemoTypeList, "Select", new { @class = "form-control", id = "ddlMemoType" })
                                </div>
                                <button type="submit" class="btn green" name="btnName" id="btnSearch"><span class="fa fa-search"></span>Search</button>
                            </div>
                            <div class="form-group">
                                
                            </div>
                            <div class="form-group">
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div id="detailInfo">
                </div>
            </div>
        </div>
    </div>
</div>
</div>

OBLContactCenter/Views/RoleActionSetting/_EditRolePartial.cshtml
@model OBLContactCenter.EFnClass.CCROLE
<script type="text/javascript">

    $("#chkIsActive").bootstrapSwitch();
    $("#chkIsAdmin").bootstrapSwitch();

    $("form").removeData("validator");
    $("form").removeData("unobtrusiveValidation");
    $.validator.unobtrusive.parse("form");

</script>
<div class="col-md-12 ">
    <div class="portlet box blue-hoki">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-grid"></i>Role Information
            </div>
        </div>
        <div class="portlet-body">

            @Html.AntiForgeryToken()
            @using (Html.BeginForm("InsertEditRole", "RoleSetting", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <div class="form-body">
                    <div id="hdnDiv" style="display: none;">
                        @Html.HiddenFor(m => m.ID);
                        @Html.HiddenFor(m => m.ISACTIVE);
                        @Html.HiddenFor(m => m.CREATEDBY);
                        @Html.HiddenFor(m => m.CREATEDON);
                        @Html.HiddenFor(m => m.MODIFIEDBY);
                        @Html.HiddenFor(m => m.MODIFIEDON);
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Role Name</label>
                        <div class="col-md-4">
                            @Html.TextBoxFor(m => m.ROLENAME, new { @class = "form-control", placeholder = "Enter Role Name" })
                            @*<input type="text" class="form-control" placeholder="Enter Employee ID/ User ID">*@
                        </div>
                        <div class="col-md-4">
                            @Html.ValidationMessageFor(m => m.ROLENAME, null, new { @class = "alert alert-danger display" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Is Admin ?</label>
                        <div class="col-md-4">
                            @Html.CheckBoxFor(m => m.ISADMIN, new { @name = "chkIsAdmin", id = "chkIsAdmin" })
                        </div>
                        <div class="col-md-4">

                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-md-3 control-label">Is Active ?</label>
                        <div class="col-md-4">
                            @Html.CheckBoxFor(m => m.ISACTIVE, new { @name = "chkIsActive", id = "chkIsActive" })
                        </div>
                        <div class="col-md-4">

                        </div>
                    </div>
                </div>
                <div class="form-actions">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            @if (Model.ID == 0)
                            {
                                <button type="submit" class="btn green" name="btnName" value="create" id="createBtn">Create</button>
                            }
                            else
                            {
                                <button type="submit" class="btn green" name="btnName" value="update" id="updateBtn">Update</button>
                            }
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

OBLContactCenter/Views/RoleActionSetting/_RolewiseActionListPartial.cshtml
@model List<OBLContactCenter.Models.RoleAction>

<div class="portlet box blue-ebonyclay">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-grid"></i>Role wise Action
             List
        </div>
    </div>

    <div class="portlet-body flip-scroll">
        @if (Model != null)
        {
            using (Html.BeginForm("SaveRoleActionList", "RoleActionSetting", FormMethod.Post, new { id = "frmRoleMenu", @class = "form-horizental" }))
            {
                var grid = new WebGrid(Model, rowsPerPage: 10, canPage: false, canSort: false);
                
            @grid.GetHtml(
                         tableStyle: "table table-bordered table-striped table-condensed flip-content",
                         headerStyle: "flip-content",

                         columns: new[]{
                             grid.Column(
                        header: "",
                        format:@<text>
            @if (item.IsAssigned == null)
                            {
<input name="chkSelect" type="checkbox" value="@item.ActionID" />
                            }
                            else
                            {
<input name="chkSelect" type="checkbox" value="@item.ActionID" checked="checked" />
                            }

            </text>
                    ),

                           grid.Column("ActionName",header: "NAME"),
                           grid.Column(format:@<input type="hidden" name="MemoTypeID" id="MemoTypeID" value="@item.MemoTypeID" />),
                           //grid.Column(null,null,format:@<input type="hidden" name="ID" id="ID" value="@item.ID" />),
            grid.Column(format:@<input type="hidden" name="RoleId" id="RoleId" value="@item.RoleId" />)
                            },
                                               mode: WebGridPagerModes.All
                                               );
               


            <div class="form-actions">
                <div class="row">
                    <div class="col-md-offset-6">

                        <button type="submit" class="btn green" name="btnName" value="update" id="btnSaveRoleMenu">Save</button>

                    </div>
                </div>
            </div>
            }
        }
        else
        {
            <div class="note note-warning">
                <h4 class="block"><span class="fa fa-warning"></span>No result found </h4>
            </div>
        }
    </div>
</div>